project:
  type: website
  output-dir: docs

website:
  title: "Abraham Flores – Data & Quantitative Analytics"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd

format:
  html:
    theme: flatly
    toc: true
    code-fold: true
    code-tools: true